openapi: "3.0.0"
info:
  title: Ping Me Notify
  version: 1.0.0
paths:
  /greeter/greet:
    get:
      summary: Ping Me Notify
      description: Ping Me Notify
      tags:
        - greeting
      parameters:
        - name: name
          in: query
          description: Name of the person to greet
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []